"""Index regeneration and log append for the Janitor (PRD §5.5.1 steps 7–8).

Rebuilds Institutional-Memory/index.md as a master catalog of all memory-tier
records, and appends a datestamped summary entry to Institutional-Memory/log.md.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import frontmatter

from lib import paths
from lib.logging import log_event

INDEX_PATH = paths.INSTITUTIONAL_MEMORY / "index.md"
LOG_PATH = paths.INSTITUTIONAL_MEMORY / "log.md"


def _gather_sources() -> list[dict[str, Any]]:
    sources_dir = paths.INSTITUTIONAL_MEMORY / "sources"
    out: list[dict[str, Any]] = []
    if not sources_dir.exists():
        return out
    for p in sorted(sources_dir.glob("src_*.md")):
        try:
            post = frontmatter.load(p)
        except Exception:
            continue
        meta = post.metadata
        out.append({
            "id": meta.get("id") or p.stem,
            "title": meta.get("title") or p.stem,
            "status": meta.get("status") or "active",
            "source_type": meta.get("source_type") or "",
            "promoted_at": str(meta.get("promoted_at") or ""),
            "tags": list(meta.get("tags") or []),
            "path": str(p.relative_to(paths.FRIDAY_ROOT)),
        })
    return out


def _gather_entities() -> list[dict[str, Any]]:
    entities_dir = paths.INSTITUTIONAL_MEMORY / "entities"
    out: list[dict[str, Any]] = []
    if not entities_dir.exists():
        return out
    for p in sorted(entities_dir.glob("*.md")):
        try:
            post = frontmatter.load(p)
        except Exception:
            continue
        meta = post.metadata
        out.append({
            "name": meta.get("name") or p.stem,
            "entity_type": meta.get("entity_type") or "",
            "sources": list(meta.get("sources") or []),
            "path": str(p.relative_to(paths.FRIDAY_ROOT)),
        })
    return out


def _gather_concepts() -> list[dict[str, Any]]:
    concepts_dir = paths.INSTITUTIONAL_MEMORY / "concepts"
    out: list[dict[str, Any]] = []
    if not concepts_dir.exists():
        return out
    for p in sorted(concepts_dir.glob("*.md")):
        try:
            post = frontmatter.load(p)
        except Exception:
            continue
        meta = post.metadata
        out.append({
            "name": meta.get("name") or p.stem,
            "sources": list(meta.get("sources") or []),
            "path": str(p.relative_to(paths.FRIDAY_ROOT)),
        })
    return out


def _build_index_text(
    sources: list[dict], entities: list[dict], concepts: list[dict],
    generated_at: str,
) -> str:
    lines = [
        "# Institutional Memory — Index",
        "",
        f"_Regenerated by Janitor at {generated_at}_",
        "",
        f"**{len(sources)} sources · {len(entities)} entities · {len(concepts)} concepts**",
        "",
    ]

    lines += ["## Sources", ""]
    if sources:
        lines.append("| ID | Title | Type | Status | Promoted |")
        lines.append("|---|---|---|---|---|")
        for s in sources:
            promoted = s["promoted_at"][:10] if s["promoted_at"] else ""
            lines.append(
                f"| [{s['id']}]({s['path']}) | {s['title']} "
                f"| {s['source_type']} | {s['status']} | {promoted} |"
            )
    else:
        lines.append("_No sources yet._")
    lines.append("")

    lines += ["## Entities", ""]
    if entities:
        lines.append("| Name | Type | Sources |")
        lines.append("|---|---|---|")
        for e in entities:
            src_count = len(e["sources"])
            lines.append(f"| [{e['name']}]({e['path']}) | {e['entity_type']} | {src_count} |")
    else:
        lines.append("_No entities yet._")
    lines.append("")

    lines += ["## Concepts", ""]
    if concepts:
        lines.append("| Name | Sources |")
        lines.append("|---|---|")
        for c in concepts:
            src_count = len(c["sources"])
            lines.append(f"| [{c['name']}]({c['path']}) | {src_count} |")
    else:
        lines.append("_No concepts yet._")
    lines.append("")

    return "\n".join(lines)


def rebuild_index(*, dry_run: bool = False) -> dict[str, int]:
    sources = _gather_sources()
    entities = _gather_entities()
    concepts = _gather_concepts()
    now_iso = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

    text = _build_index_text(sources, entities, concepts, now_iso)
    counts = {"sources": len(sources), "entities": len(entities), "concepts": len(concepts)}

    if dry_run:
        print(f"  [dry-run] index: {counts['sources']} sources, "
              f"{counts['entities']} entities, {counts['concepts']} concepts")
        return counts

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(text, encoding="utf-8")
    log_event("janitor.index", "rebuilt", **counts)
    return counts


def append_log(summary: str, *, dry_run: bool = False) -> None:
    """Append a datestamped entry to Institutional-Memory/log.md."""
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    entry = f"\n## {date_str}\n\n{summary}\n"

    if dry_run:
        print(f"  [dry-run] would append to log.md:\n{entry}")
        return

    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not LOG_PATH.exists():
        LOG_PATH.write_text("# Operations Log\n\nChronological log of automated operations.\n", encoding="utf-8")

    existing = LOG_PATH.read_text(encoding="utf-8")
    if existing.strip() == "# Operations Log\n\nChronological log of automated operations: ingests, promotions, demotions, sweeps, conflicts.\n\n_Empty — no operations yet._":
        LOG_PATH.write_text("# Operations Log\n\nChronological log of automated operations.\n" + entry, encoding="utf-8")
    else:
        LOG_PATH.write_text(existing.rstrip() + "\n" + entry, encoding="utf-8")
